### ISSUE TITLE
Download Freeze

### ISSUE THREAD

**Issue by nateg2** [dannysmc95/AppStoreCC#1]
@dannysmc95 as seen in website issue here is a simple gif. Shows better understanding of how and when it freezes

Had to use Ctrl-T to exit
![ezgif com-video-to-gif](https://github-cloud.s3.amazonaws.com/assets/15174488/10565731/00b9acf0-75a6-11e5-8434-c1188b4c30b8.gif)

**Comment by dannysmc95** [comment]
Interesting I have not seen that bug, looks like it is stuck in some loop where it has not switched the thread, will have a look for you, thanks for reporting this.
